package:
  name: catatonit
  version: 0.2.1
  description: minimal init system for Linux containers
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - ca-certificates-bundle
      - build-base
      - busybox
      - bash
      - gpg
      - gpg-agent
      - gnupg-dirmngr
      - curl
      - libtool

pipeline:
  - name: Download release tarball
    uses: fetch
    with:
      uri: https://github.com/openSUSE/${{package.name}}/releases/download/v${{package.version}}/catatonit.tar.xz
      expected-sha256: 9950425501af862e12f618bdc930ea755c46db6a16072a1462b4fc93b2bd59bc
  
  - name: Download PGP signature
    runs: |
      curl -fsSLO "https://github.com/openSUSE/${{package.name}}/releases/download/v${{package.version}}/catatonit.tar.xz.asc"
  
  - name: Import PGP public key
    runs: |
      gpg --keyserver keyserver.ubuntu.com --recv-keys 5F36C6C61B5460124A75F5A69E18AA267DDB8DB4
  
  - name: Verify PGP signature
    runs: |
      gpg --verify catatonit.tar.xz.asc catatonit.tar.xz

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip
